/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import jakarta.persistence.EntityManager;
import jakarta.persistence.Persistence;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julia Freitas
 */
public class CursoListar extends javax.swing.JFrame {
    private final CursoIController cursoController = new CursoController();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());

    /**
     * Creates new form CursoListar
     */
    public CursoListar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Quantidade", "Descrição", "Instituição", "Remover", "Editar"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 700, 375));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setText("PROCURAR");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 47, -1, -1));

        jButton1.setText("+");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 32, 28));

        jButton2.setText("PESQUISAR");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
    String nome = jTextField1.getText();

    try {
        List<Curso> lista;

        if (nome == null || nome.trim().isEmpty()) {
            lista = cursoController.findAll();
        } else {
            lista = cursoController.findByNome(nome); // (se implementar)
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);

        for (Curso c : lista) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getQuantidade(),
                c.getDescricao(),
                c.getInstituicao(),
                "Remover",
                "Editar"
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Cria uma nova instância da tela de cadastro de curso
    CursoSave telaCadastro = new CursoSave();

    // Centraliza a janela na tela (opcional, mas recomendado)
    telaCadastro.setLocationRelativeTo(null);

    // Torna a janela visível para o usuário
    telaCadastro.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int linha = jTable1.getSelectedRow();
    int coluna = jTable1.getSelectedColumn();
    
    // Supondo que a coluna 4 seja a Lixeira (Remover)
    if (coluna == 4) { 
        removerCurso(linha);
    }
    
    // Supondo que a coluna 5 seja o Lápis (Editar)
    if (coluna == 5) {
        editarCurso(linha);
    }
    }//GEN-LAST:event_jTable1MouseClicked
   private void removerCurso(int linha) {
    Long id = (Long) jTable1.getValueAt(linha, 0);

    int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este curso?");

    if (resposta == JOptionPane.YES_OPTION) {
        try {
            Curso curso = cursoController.findById(id);
            cursoController.delete(curso);

            JOptionPane.showMessageDialog(this, "Curso removido com sucesso!");
            atualizarTabela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao remover: " + e.getMessage());
        }
    }
}
    
    private void editarCurso(int linha) {
    Long id = (Long) jTable1.getValueAt(linha, 0);
    
    // Aqui você pode apenas abrir a tela de cadastro para o usuário editar
    // Ou pode buscar o curso e passar para a tela de salvar
    CursoSave telaSalvar = new CursoSave();
    telaSalvar.setVisible(true);
    
    // Dica: Para um sistema real, você passaria o ID para o CursoSave
    // para ele carregar os dados nos campos de texto.
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoListar().setVisible(true));
    }
    
   
    public void atualizarTabela() {
    try {
        List<Curso> lista = cursoController.findAll();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);

        for (Curso c : lista) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getQuantidade(),
                c.getDescricao(),
                c.getInstituicao(),
                "Remover",
                "Editar"
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao listar: " + e.getMessage());
    }
}

    
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
